# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

emotion1 = Emotion.create(name: 'happy')
emotion2 = Emotion.create(name: 'sad')

# Happy Images #

image1  = Image.create(name: 'are-you-happy', 		file: "https://s3.amazonaws.com/emotionsproject/happy/are-you-happy.jpg")
image2  = Image.create(name: 'be-happy', 					file: "https://s3.amazonaws.com/emotionsproject/happy/be_happy-wallpaper.jpg")
image3  = Image.create(name: 'because-im-happy', 	file: "https://s3.amazonaws.com/emotionsproject/happy/because-im-happy.jpg")
image4  = Image.create(name: 'birthday=mouse', 		file: "https://s3.amazonaws.com/emotionsproject/happy/birthday-mouse.jpg")
image5  = Image.create(name: 'cat-glasses', 			file: "https://s3.amazonaws.com/emotionsproject/happy/cat-glasses.jpg")
image6  = Image.create(name: 'cereal-smiley', 		file: "https://s3.amazonaws.com/emotionsproject/happy/cereal-smiley.jpg")
image7  = Image.create(name: 'chamomile', 				file: "https://s3.amazonaws.com/emotionsproject/happy/chamomile.jpg")
image8  = Image.create(name: 'color-run', 				file: "https://s3.amazonaws.com/emotionsproject/happy/color-run.jpg")
image9  = Image.create(name: 'finger-friends', 		file: "https://s3.amazonaws.com/emotionsproject/happy/finger-friends.jpg")
image10 = Image.create(name: 'funny-kitten', 			file: "https://s3.amazonaws.com/emotionsproject/happy/funny-kitten.jpg")
image11 = Image.create(name: 'happy-1', 					file: "https://s3.amazonaws.com/emotionsproject/happy/happy-1.jpg")
image12 = Image.create(name: 'happy-baby', 				file: "https://s3.amazonaws.com/emotionsproject/happy/happy-baby.jpg")
image13 = Image.create(name: 'happy-cat', 				file: "https://s3.amazonaws.com/emotionsproject/happy/happy-cat.jpg")
image14 = Image.create(name: 'happy-child', 			file: "https://s3.amazonaws.com/emotionsproject/happy/happy-child.jpg")
image15 = Image.create(name: 'happy-dog', 				file: "https://s3.amazonaws.com/emotionsproject/happy/happy-dog.jpg")
image16 = Image.create(name: 'happy-family', 			file: "https://s3.amazonaws.com/emotionsproject/happy/happy-family.jpg")
image17 = Image.create(name: 'happy-feet', 				file: "https://s3.amazonaws.com/emotionsproject/happy/happy-feet.jpg")
image18 = Image.create(name: 'happy-love', 				file: "https://s3.amazonaws.com/emotionsproject/happy/happy-love.jpg")
image19 = Image.create(name: 'happy-smiley', 			file: "https://s3.amazonaws.com/emotionsproject/happy/happy-smiley.jpg")
image20 = Image.create(name: 'happy-sun', 				file: "https://s3.amazonaws.com/emotionsproject/happy/happy-sun.jpg")
image21 = Image.create(name: 'like-a-child', 			file: "https://s3.amazonaws.com/emotionsproject/happy/like-a-child.jpg")
image22 = Image.create(name: 'married-barefoot',	file: "https://s3.amazonaws.com/emotionsproject/happy/married-barefoot.jpg")
image23 = Image.create(name: 'minions', 					file: "https://s3.amazonaws.com/emotionsproject/happy/minions.jpg")
image24 = Image.create(name: 'pink-smiley', 			file: "https://s3.amazonaws.com/emotionsproject/happy/pink-smiley.jpg")
image25 = Image.create(name: 'winter-happiness', 	file: "https://s3.amazonaws.com/emotionsproject/happy/winter-happiness.jpg")

# Happy ImageEmotions #

imageEmotion1  = ImageEmotion.create(image_id: 1,  emotion_id: 1)
imageEmotion2  = ImageEmotion.create(image_id: 2,  emotion_id: 1)
imageEmotion3  = ImageEmotion.create(image_id: 3,  emotion_id: 1)
imageEmotion4  = ImageEmotion.create(image_id: 4,  emotion_id: 1)
imageEmotion5  = ImageEmotion.create(image_id: 5,  emotion_id: 1)
imageEmotion6  = ImageEmotion.create(image_id: 6,  emotion_id: 1)
imageEmotion7  = ImageEmotion.create(image_id: 7,  emotion_id: 1)
imageEmotion8  = ImageEmotion.create(image_id: 8,  emotion_id: 1)
imageEmotion9  = ImageEmotion.create(image_id: 9,  emotion_id: 1)
imageEmotion10 = ImageEmotion.create(image_id: 10, emotion_id: 1)
imageEmotion11 = ImageEmotion.create(image_id: 11, emotion_id: 1)
imageEmotion12 = ImageEmotion.create(image_id: 12, emotion_id: 1)
imageEmotion13 = ImageEmotion.create(image_id: 13, emotion_id: 1)
imageEmotion14 = ImageEmotion.create(image_id: 14, emotion_id: 1)
imageEmotion15 = ImageEmotion.create(image_id: 15, emotion_id: 1)
imageEmotion16 = ImageEmotion.create(image_id: 16, emotion_id: 1)
imageEmotion17 = ImageEmotion.create(image_id: 17, emotion_id: 1)
imageEmotion18 = ImageEmotion.create(image_id: 18, emotion_id: 1)
imageEmotion19 = ImageEmotion.create(image_id: 19, emotion_id: 1)
imageEmotion20 = ImageEmotion.create(image_id: 20, emotion_id: 1)
imageEmotion21 = ImageEmotion.create(image_id: 21, emotion_id: 1)
imageEmotion22 = ImageEmotion.create(image_id: 22, emotion_id: 1)
imageEmotion23 = ImageEmotion.create(image_id: 23, emotion_id: 1)
imageEmotion24 = ImageEmotion.create(image_id: 24, emotion_id: 1)
imageEmotion25 = ImageEmotion.create(image_id: 25, emotion_id: 1)


# Sad Images #

image26 = Image.create(name: 'balloon', 					file: "https://s3.amazonaws.com/emotionsproject/sad/balloon.jpg")
image27 = Image.create(name: 'bird-rain', 				file: "https://s3.amazonaws.com/emotionsproject/sad/bird-in-rain.jpg")
image28 = Image.create(name: 'elephant', 					file: "https://s3.amazonaws.com/emotionsproject/sad/elephant.jpg")
image29 = Image.create(name: 'foggy-day', 				file: "https://s3.amazonaws.com/emotionsproject/sad/foggy-day.jpg")
image30 = Image.create(name: 'girl-rain', 				file: "https://s3.amazonaws.com/emotionsproject/sad/girl-rain.jpg")
image31 = Image.create(name: 'lonely-corner', 		file: "https://s3.amazonaws.com/emotionsproject/sad/lonely-corner.jpg")
image32 = Image.create(name: 'main-rain', 				file: "https://s3.amazonaws.com/emotionsproject/sad/man-rain.jpg")
image33 = Image.create(name: 'moments', 					file: "https://s3.amazonaws.com/emotionsproject/sad/moments.jpg")
image34 = Image.create(name: 'puppy-eyes', 				file: "https://s3.amazonaws.com/emotionsproject/sad/puppy-eyes.jpg")
image35 = Image.create(name: 'sad-angel', 				file: "https://s3.amazonaws.com/emotionsproject/sad/sad-angel.jpg")
image36 = Image.create(name: 'sad-boy-clown', 		file: "https://s3.amazonaws.com/emotionsproject/sad/sad-boy-clown.jpg")
image37 = Image.create(name: 'sad-cat', 					file: "https://s3.amazonaws.com/emotionsproject/sad/sad-cat.jpg")
image38 = Image.create(name: 'sad-chibi', 				file: "https://s3.amazonaws.com/emotionsproject/sad/sad-chibi.jpg")
image39 = Image.create(name: 'sad-child', 				file: "https://s3.amazonaws.com/emotionsproject/sad/sad-child.jpg")
image40 = Image.create(name: 'sad-danbo', 				file: "https://s3.amazonaws.com/emotionsproject/sad/sad-danbo.jpg")
image41 = Image.create(name: 'sad-dog', 					file: "https://s3.amazonaws.com/emotionsproject/sad/sad-dog.jpg")
image42 = Image.create(name: 'sad-kitty', 				file: "https://s3.amazonaws.com/emotionsproject/sad/sad-kitty.jpg")
image43 = Image.create(name: 'sad-rain', 					file: "https://s3.amazonaws.com/emotionsproject/sad/sad-rain.jpg")
image44 = Image.create(name: 'sad-robot', 				file: "https://s3.amazonaws.com/emotionsproject/sad/sad-robot.jpg")
image45 = Image.create(name: 'sad-sketch',				file: "https://s3.amazonaws.com/emotionsproject/sad/sad-sketch.jpg")
image46 = Image.create(name: 'sad-tree', 					file: "https://s3.amazonaws.com/emotionsproject/sad/sad-tree.jpg")
image47 = Image.create(name: 'tear', 							file: "https://s3.amazonaws.com/emotionsproject/sad/tear.jpg")

# Sad ImageEmotions #

imageEmotion26 = ImageEmotion.create(image_id: 26, emotion_id: 2)
imageEmotion27 = ImageEmotion.create(image_id: 27, emotion_id: 2)
imageEmotion28 = ImageEmotion.create(image_id: 28, emotion_id: 2)
imageEmotion29 = ImageEmotion.create(image_id: 29, emotion_id: 2)
imageEmotion30 = ImageEmotion.create(image_id: 30, emotion_id: 2)
imageEmotion31 = ImageEmotion.create(image_id: 31, emotion_id: 2)
imageEmotion32 = ImageEmotion.create(image_id: 32, emotion_id: 2)
imageEmotion33 = ImageEmotion.create(image_id: 33, emotion_id: 2)
imageEmotion34 = ImageEmotion.create(image_id: 34, emotion_id: 2)
imageEmotion35 = ImageEmotion.create(image_id: 35, emotion_id: 2)
imageEmotion36 = ImageEmotion.create(image_id: 36, emotion_id: 2)
imageEmotion37 = ImageEmotion.create(image_id: 37, emotion_id: 2)
imageEmotion38 = ImageEmotion.create(image_id: 38, emotion_id: 2)
imageEmotion39 = ImageEmotion.create(image_id: 39, emotion_id: 2)
imageEmotion40 = ImageEmotion.create(image_id: 40, emotion_id: 2)
imageEmotion41 = ImageEmotion.create(image_id: 41, emotion_id: 2)
imageEmotion42 = ImageEmotion.create(image_id: 42, emotion_id: 2)
imageEmotion43 = ImageEmotion.create(image_id: 43, emotion_id: 2)
imageEmotion44 = ImageEmotion.create(image_id: 44, emotion_id: 2)
imageEmotion45 = ImageEmotion.create(image_id: 45, emotion_id: 2)
imageEmotion46 = ImageEmotion.create(image_id: 46, emotion_id: 2)
imageEmotion47 = ImageEmotion.create(image_id: 47, emotion_id: 2)

# Happy Music #

music1 = Music.create(name: 'Happy by Pharrell Williams', file: "")
music2 = Music.create(name: 'The Man by Aloe Blacc', file: "")
music3 = Music.create(name: 'Fascination by Alphabeat')
music4 = Music.create(name: 'Chewing Gum by Annie', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/01+Chewing+Gum.mp3")
music5 = Music.create(name: 'Happy Together by The Turtles')
music6 = Music.create(name: 'Dont Worry, Be Happy by Bobby McFerrin', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/01+Don%27t+Worry%2C+Be+Happy.mp3")
music7 = Music.create(name: 'Happy Days by Pratt & McClain')
music8 = Music.create(name: 'Wake Me Up Before You Go Go by Wham!')
music9 = Music.create(name: 'Walking On Sunshine by Katrina & The Waves')
music10 = Music.create(name: 'And We Danced by Macklemore', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/And+We+Danced+(feat.+Ziggy+Stardust).mp3")
music11 = Music.create(name: 'Marry You by Bruno Mars', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/06+Marry+You.mp3")
music12 = Music.create(name: 'One Week by Barenaked Ladies', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/01+One+Week.mp3")
music13 = Music.create(name: 'Best Day of My Life by American Authors', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Best+Day+of+My+Life.mp3")
music14 = Music.create(name: 'Love On Top by Beyonce')
music15 = Music.create(name: 'I Will Never Let You Down by Rita Ora')
music16 = Music.create(name: 'Mr. Blue Sky by Electric Light Orchestra')
music17 = Music.create(name: 'My Girl by The Temptations')
music18 = Music.create(name: 'Steal My Sunshine by LEN')
music19 = Music.create(name: 'Shake It Off by Taylor Swift')
music20 = Music.create(name: 'Dance Apocalyptic by Janelle Monae', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Dance+Apocalyptic.mp3")
music21 = Music.create(name: 'Carried Away by Passion Pit', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Carried+Away.mp3")
music22 = Music.create(name: 'Good Luck by Basement Jaxx')
music23 = Music.create(name: 'Flaws by Bastille')
music24 = Music.create(name: 'I Gotta Feeling by Black Eyed Peas')
music25 = Music.create(name: 'I Wanna Get Better by Bleachers')
music26 = Music.create(name: 'Hey Leonardo (She Likes Me For Me) by Bless Union Of Souls')
music27 = Music.create(name: 'Run Around by Blues Traveler', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/01+Run+Around.mp3")
music28 = Music.create(name: 'Summer by Calvin Harris')
music29 = Music.create(name: 'Fuck You by Cee Lo Green')
music30 = Music.create(name: 'I Belong In Your Arms by Chairlift')
music31 = Music.create(name: 'Boom Clap by Charli XCX', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Boom+Clap.mp3")
music32 = Music.create(name: 'Rather Be by Clean Bandit')
music33 = Music.create(name: 'Gold Rush by Clinton Sparks')
music34 = Music.create(name: 'You Make Me Feel... by Cobra Starship')
music35 = Music.create(name: 'Every Teardrop Is a Waterfall by Coldplay', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Every+Teardrop+Is+a+Waterfall.mp3")
music36 = Music.create(name: 'Put Your Records On by Corinne Bailey Rae')
music37 = Music.create(name: 'Accidentally In Love by Counting Crows', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/01+Accidentally+in+Love.mp3")
music38 = Music.create(name: 'Get Lucky by Daft Punk')
music39 = Music.create(name: 'Life, Love & Laughter by Donavon Frankenreiter', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/01+Life%2C+Love+%26+Laughter.mp3")
music40 = Music.create(name: 'Sing by Ed Sheeran')
music41 = Music.create(name: 'Anything Could Happen by Ellie Goulding', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Anything+Could+Happen.mp3")
music42 = Music.create(name: 'Dont Stop by Fleetwood Mac', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Don%27t+Stop.mp3")
music43 = Music.create(name: 'Dog Days Are Over by Florence & The Machine', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Dog+Days+Are+Over.mp3")
music44 = Music.create(name: 'We Are Young by Fun.')
music45 = Music.create(name: 'Best I Ever Had by Gavin DeGraw', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Best+I+Ever+Had.mp3")
music46 = Music.create(name: 'Love Love Love by Hope')
music47 = Music.create(name: 'I Love It (I Dont Care) by Icona Pop')
music48 = Music.create(name: 'Fancy by Iggy Azalea')
music49 = Music.create(name: 'On Top of the World by Imagine Dragons')
music50 = Music.create(name: 'Staple It Together by Jack Johnson', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/07+Staple+It+Together.mp3")
music51 = Music.create(name: 'Geek In the Pink by Jason Mraz')
music52 = Music.create(name: 'Bang Bang by Jessie J', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Bang+Bang+(feat.+Ariana+Grande+%26+Nicki+Minaj).mp3")
music53 = Music.create(name: 'No Such Thing by John Mayer')
music54 = Music.create(name: 'Some Kind of Wonderful by Joss Stone')
music55 = Music.create(name: 'Dont Stop Believin by Journey', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Don%27t+Stop+Believin%27.mp3")
music56 = Music.create(name: 'Last Friday Night by Katy Perry')
music57 = Music.create(name: 'Tralala by Kiah Victoria')
music58 = Music.create(name: 'Up Up & Away by Kid Cudi')
music59 = Music.create(name: 'Hideaway by Kiesza')
music60 = Music.create(name: 'Wings by Little Mix')
music61 = Music.create(name: 'Daydreamin by Lupe Fiasco', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Daydreamin%27+(feat.+Jill+Scott).mp3")
music62 = Music.create(name: 'Moves Like Jagger by Maroon 5')
music63 = Music.create(name: 'All About That Bass by Meghan Trainor', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/All+About+That+Bass.mp3")
music64 = Music.create(name: 'Electric Feel by MGMT', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Electric+Feel.mp3")
music65 = Music.create(name: 'Love Never Felt So Good by Michael Jackson & Justin Timberlake')
music66 = Music.create(name: 'Grace Kelly by Mika')
music67 = Music.create(name: 'You Get What You Give by New Radicals')
music68 = Music.create(name: 'She is Electric by Oasis')
music69 = Music.create(name: 'Little Talks by Of Monsters And Men')
music70 = Music.create(name: 'Live While We Are Young by One Direction')
music71 = Music.create(name: 'Counting Stars by OneRepublic', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Counting+Stars.mp3")
music72 = Music.create(name: 'Lisztomania by Phoenix')
music73 = Music.create(name: 'King of Anything by Sara Bareilles')
music74 = Music.create(name: 'Hall of Fame by The Script')
music75 = Music.create(name: 'Up! by Shania Twain')
music76 = Music.create(name: 'Closer by Tegan and Sara', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Closer.mp3")
music77 = Music.create(name: 'If Its Love by Train')
music78 = Music.create(name: 'Island In the Sun by Weezer')
music79 = Music.create(name: 'Bang Bang by will.i.am', file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Bang+Bang.mp3")

# Happy MusicEmotions #
musicEmotions1 = MusicEmotion.create(music_id: 1, emotion_id: 1)
musicEmotions2 = MusicEmotion.create(music_id: 2, emotion_id: 1)
musicEmotions3 = MusicEmotion.create(music_id: 3, emotion_id: 1)
musicEmotions4 = MusicEmotion.create(music_id: 4, emotion_id: 1)
musicEmotions5 = MusicEmotion.create(music_id: 5, emotion_id: 1)
musicEmotions6 = MusicEmotion.create(music_id: 6, emotion_id: 1)
musicEmotions7 = MusicEmotion.create(music_id: 7, emotion_id: 1)
musicEmotions8 = MusicEmotion.create(music_id: 8, emotion_id: 1)
musicEmotions9 = MusicEmotion.create(music_id: 9, emotion_id: 1)
musicEmotions10 = MusicEmotion.create(music_id: 10, emotion_id: 1)
musicEmotions11 = MusicEmotion.create(music_id: 11, emotion_id: 1)
musicEmotions12 = MusicEmotion.create(music_id: 12, emotion_id: 1)
musicEmotions13 = MusicEmotion.create(music_id: 13, emotion_id: 1)
musicEmotions14 = MusicEmotion.create(music_id: 14, emotion_id: 1)
musicEmotions15 = MusicEmotion.create(music_id: 15, emotion_id: 1)
musicEmotions16 = MusicEmotion.create(music_id: 16, emotion_id: 1)
musicEmotions17 = MusicEmotion.create(music_id: 17, emotion_id: 1)
musicEmotions18 = MusicEmotion.create(music_id: 18, emotion_id: 1)
musicEmotions19 = MusicEmotion.create(music_id: 19, emotion_id: 1)
musicEmotions20 = MusicEmotion.create(music_id: 20, emotion_id: 1)
musicEmotions21 = MusicEmotion.create(music_id: 21, emotion_id: 1)
musicEmotions22 = MusicEmotion.create(music_id: 22, emotion_id: 1)
musicEmotions23 = MusicEmotion.create(music_id: 23, emotion_id: 1)
musicEmotions24 = MusicEmotion.create(music_id: 24, emotion_id: 1)
musicEmotions25 = MusicEmotion.create(music_id: 25, emotion_id: 1)
musicEmotions26 = MusicEmotion.create(music_id: 26, emotion_id: 1)
musicEmotions27 = MusicEmotion.create(music_id: 27, emotion_id: 1)
musicEmotions28 = MusicEmotion.create(music_id: 28, emotion_id: 1)
musicEmotions29 = MusicEmotion.create(music_id: 29, emotion_id: 1)
musicEmotions30 = MusicEmotion.create(music_id: 30, emotion_id: 1)
musicEmotions31 = MusicEmotion.create(music_id: 31, emotion_id: 1)
musicEmotions32 = MusicEmotion.create(music_id: 32, emotion_id: 1)
musicEmotions33 = MusicEmotion.create(music_id: 33, emotion_id: 1)
musicEmotions34 = MusicEmotion.create(music_id: 34, emotion_id: 1)
musicEmotions35 = MusicEmotion.create(music_id: 35, emotion_id: 1)
musicEmotions36 = MusicEmotion.create(music_id: 36, emotion_id: 1)
musicEmotions37 = MusicEmotion.create(music_id: 37, emotion_id: 1)
musicEmotions38 = MusicEmotion.create(music_id: 38, emotion_id: 1)
musicEmotions39 = MusicEmotion.create(music_id: 39, emotion_id: 1)
musicEmotions40 = MusicEmotion.create(music_id: 40, emotion_id: 1)
musicEmotions41 = MusicEmotion.create(music_id: 41, emotion_id: 1)
musicEmotions42 = MusicEmotion.create(music_id: 42, emotion_id: 1)
musicEmotions43 = MusicEmotion.create(music_id: 43, emotion_id: 1)
musicEmotions44 = MusicEmotion.create(music_id: 44, emotion_id: 1)
musicEmotions45 = MusicEmotion.create(music_id: 45, emotion_id: 1)
musicEmotions46 = MusicEmotion.create(music_id: 46, emotion_id: 1)
musicEmotions47 = MusicEmotion.create(music_id: 47, emotion_id: 1)
musicEmotions48 = MusicEmotion.create(music_id: 48, emotion_id: 1)
musicEmotions49 = MusicEmotion.create(music_id: 49, emotion_id: 1)
musicEmotions50 = MusicEmotion.create(music_id: 50, emotion_id: 1)
musicEmotions51 = MusicEmotion.create(music_id: 51, emotion_id: 1)
musicEmotions52 = MusicEmotion.create(music_id: 52, emotion_id: 1)
musicEmotions53 = MusicEmotion.create(music_id: 53, emotion_id: 1)
musicEmotions54 = MusicEmotion.create(music_id: 54, emotion_id: 1)
musicEmotions55 = MusicEmotion.create(music_id: 55, emotion_id: 1)
musicEmotions56 = MusicEmotion.create(music_id: 56, emotion_id: 1)
musicEmotions57 = MusicEmotion.create(music_id: 57, emotion_id: 1)
musicEmotions58 = MusicEmotion.create(music_id: 58, emotion_id: 1)
musicEmotions59 = MusicEmotion.create(music_id: 59, emotion_id: 1)
musicEmotions60 = MusicEmotion.create(music_id: 60, emotion_id: 1)
musicEmotions61 = MusicEmotion.create(music_id: 61, emotion_id: 1)
musicEmotions62 = MusicEmotion.create(music_id: 62, emotion_id: 1)
musicEmotions63 = MusicEmotion.create(music_id: 63, emotion_id: 1)
musicEmotions64 = MusicEmotion.create(music_id: 64, emotion_id: 1)
musicEmotions65 = MusicEmotion.create(music_id: 65, emotion_id: 1)
musicEmotions66 = MusicEmotion.create(music_id: 66, emotion_id: 1)
musicEmotions67 = MusicEmotion.create(music_id: 67, emotion_id: 1)
musicEmotions68 = MusicEmotion.create(music_id: 68, emotion_id: 1)
musicEmotions69 = MusicEmotion.create(music_id: 69, emotion_id: 1)
musicEmotions70 = MusicEmotion.create(music_id: 70, emotion_id: 1)
musicEmotions71 = MusicEmotion.create(music_id: 71, emotion_id: 1)
musicEmotions72 = MusicEmotion.create(music_id: 72, emotion_id: 1)
musicEmotions73 = MusicEmotion.create(music_id: 73, emotion_id: 1)
musicEmotions74 = MusicEmotion.create(music_id: 74, emotion_id: 1)
musicEmotions75 = MusicEmotion.create(music_id: 75, emotion_id: 1)
musicEmotions76 = MusicEmotion.create(music_id: 76, emotion_id: 1)
musicEmotions77 = MusicEmotion.create(music_id: 77, emotion_id: 1)
musicEmotions78 = MusicEmotion.create(music_id: 78, emotion_id: 1)
musicEmotions79 = MusicEmotion.create(music_id: 79, emotion_id: 1)



video1 = Video.create(name: 'Minions Working Out', file: "www.youtube.com/embed/KLMJPKylg2Y")
video2 = Video.create(name: "Saddest Commercial You'll Ever See", file: "www.youtube.com/embed/EEYm2zA7h_k")
video3 = Video.create(name: 'Just a very Sad Story', file: "www.youtube.com/embed/jXmluLg2XP0")
video4 = Video.create(name: "Collection of happy videos", file: "www.youtube.com/embed/3jRiRHwL7xM")
video5 = Video.create(name: "Happy Dogs", file: "www.youtube.com/embed/hGyZ2ETCTVU")
video6 = Video.create(name: "Brian Williams Rapping", file: "www.youtube.com/embed/-YCeIgt7hMs")
video7 = Video.create(name: "Happy at the Thrift Shop :)", file: "www.youtube.com/embed/QK8mJJJvaes")
video8 = Video.create(name: "BBMak Out of My Heart - happy song", file: "www.youtube.com/embed/I6BafxPK5pE?list=FLHgMBFypW4xk6hCTycP-C6g")
video9 = Video.create(name: "Darth kid", file: "www.youtube.com/embed/R55e-uHQna0?list=FLHgMBFypW4xk6hCTycP-C6g")
video10 = Video.create(name: "Couple's song", file: "www.youtube.com/embed/UFbQ3UbkYGo?list=FLHgMBFypW4xk6hCTycP-C6g")
video11 = Video.create(name: "Final Fantasy 8 happy ending with Aerosmith", file: "www.youtube.com/embed/vOFjLHU9in4?list=FLHgMBFypW4xk6hCTycP-C6g")
video12 = Video.create(name: "Kenny Chesney - Good Stuff", file: "www.youtube.com/embed/lYQZJ9NUzYU")
video13 = Video.create(name: "Bullying", file: "www.youtube.com/embed/q4syd4vKFPE")
video14 = Video.create(name: "Father and Son", file: "www.youtube.com/embed/1BZmuz88KEY")
video15 = Video.create(name: "Story about suicide", file: "www.youtube.com/embed/aMqFflLJN38")
video16 = Video.create(name: "Man loses his life and love", file: "www.youtube.com/embed/_Ef8ZHgxxK0")
video17 = Video.create(name: "Raymond Lam wonders about someone else's life", file: "www.youtube.com/embed/cBNXAxjabw0")
video18 = Video.create(name: "Five for Fighting's Augie Nieto", file: "www.youtube.com/embed/dJsm31yw4Uo?list=FLHgMBFypW4xk6hCTycP-C6g")
video19 = Video.create(name: "Sam and Annie - Life on Mars", file: "www.youtube.com/embed/xBm-WWY87r8")
video20 = Video.create(name: "Ray Lam If The Time Ever Arrives", file: "www.youtube.com/embed/Fawpke7fJDw")
video21 = Video.create(name: "Father who is blind", file: "www.youtube.com/embed/SV6Sw9CNWek")
video22 = Video.create(name: "Bruno Mars Talking to the Moon", file: "www.youtube.com/embed/K59Tmrs9YD0")
video23 = Video.create(name: "Lonestar - I'm Already There", file: "www.youtube.com/embed/1jm5gfuT9Z4")
video24 = Video.create(name: "lego starwars", file: "www.youtube.com/embed/z0z_TU4Gw5o?list=FLHgMBFypW4xk6hCTycP-C6g")
video25 = Video.create(name: "Johnny Cash - Hurt", file: "www.youtube.com/embed/3aF9AJm0RFc")
 


videoEmotion1 = VideoEmotion.create(video_id: 1, emotion_id: 1)
videoEmotion2 = VideoEmotion.create(video_id: 2, emotion_id: 2)
videoEmotion3 = VideoEmotion.create(video_id: 3, emotion_id: 2)
videoEmotion4 = VideoEmotion.create(video_id: 4, emotion_id: 1)
videoEmotion5 = VideoEmotion.create(video_id: 5, emotion_id: 1)
videoEmotion6 = VideoEmotion.create(video_id: 6, emotion_id: 1)
videoEmotion7 = VideoEmotion.create(video_id: 7, emotion_id: 1)
videoEmotion8 = VideoEmotion.create(video_id: 8, emotion_id: 1)
videoEmotion9 = VideoEmotion.create(video_id: 9, emotion_id: 1)
videoEmotion10 = VideoEmotion.create(video_id: 10, emotion_id: 1)
videoEmotion11 = VideoEmotion.create(video_id: 11, emotion_id: 1)
videoEmotion12 = VideoEmotion.create(video_id: 12, emotion_id: 1)
videoEmotion13 = VideoEmotion.create(video_id: 13, emotion_id: 2)
videoEmotion14 = VideoEmotion.create(video_id: 14, emotion_id: 2)
videoEmotion15 = VideoEmotion.create(video_id: 15, emotion_id: 2)
videoEmotion16 = VideoEmotion.create(video_id: 16, emotion_id: 2)
videoEmotion17 = VideoEmotion.create(video_id: 17, emotion_id: 2)
videoEmotion18 = VideoEmotion.create(video_id: 18, emotion_id: 2)
videoEmotion19 = VideoEmotion.create(video_id: 19, emotion_id: 2)
videoEmotion20 = VideoEmotion.create(video_id: 20, emotion_id: 2)
videoEmotion21 = VideoEmotion.create(video_id: 21, emotion_id: 2)
videoEmotion22 = VideoEmotion.create(video_id: 22, emotion_id: 2)
videoEmotion23 = VideoEmotion.create(video_id: 23, emotion_id: 2)
videoEmotion24 = VideoEmotion.create(video_id: 24, emotion_id: 3) 
videoEmotion25 = VideoEmotion.create(video_id: 24, emotion_id: 2) 
